### ISSUE TITLE
проблема с null/null - badarith, div - создается пустой объект, удалить не получается.

### ISSUE THREAD

**Issue by AzamatIlyasov** [vzroman/ecomet#16]
Возможно в Ecomet или в сопутствующей программе есть проблема - если каким то образом создается пустой объект - то его через web не получается удалить 

это на примере ALARMS/LOG/
но такое поведение бывали и в других местах

**Как удалить такие объекты - починить базу - без удаления базы?**

- выдается ошибка:

_`{badarith,[{erlang,'div',[none,1099511627776],[]}, {ecomet_object,get_pattern_oid,1, [{file,"/opt/ext/faceplate/develop/faceplate/_build/default/lib/ecomet/src/ecomet_object.erl"}, {line,974}]}, {ecomet_object,construct,1, [{file,"/opt/ext/faceplate/develop/faceplate/_build/default/lib/ecomet/src/ecomet_object.erl"}, {line,1001}]}, {ecomet_object,check_rights,1, [{file,"/opt/ext/faceplate/develop/faceplate/_build/default/lib/ecomet/src/ecomet_object.erl"}, {line,504}]}, {ecomet_object,open,3, [{file,"/opt/ext/faceplate/develop/faceplate/_build/default/lib/ecomet/src/ecomet_object.erl"}, {line,238}]}, {ecomet_json,'-handle/3-fun-1-',1, [{file,"/opt/ext/faceplate/develop/faceplate/_build/default/lib/ecomet/src/ecomet_json.erl"}, {line,117}]}, {ecomet_transaction,'-internal/1-fun-0-',2, [{file,"/opt/ext/faceplate/develop/faceplate/_build/default/lib/ecomet/src/ecomet_transaction.erl"}, {line,55}]}, {mnesia_tm,apply_fun,3, [{file,"/opt/ext/faceplate/develop/faceplate/_build/default/lib/mnesia/src/mnesia_tm.erl"}, {line,928}]}]}`_

вот скрины:

![image](https://user-images.githubusercontent.com/26342276/168876494-8144d674-7527-43fe-a7a3-932e0003d214.png)

![image](https://user-images.githubusercontent.com/26342276/168876191-5c355c61-650b-4d68-9cf3-20ca6d54aded.png)

**Comment by vzroman** [comment]
Resolved in v0.2.0
